/**
 * As constantes do sistema
 */
export const LanguageConstants = {
  REGISTER: "REGISTER",
  BOOK: "BOOK",
  COLLECTION: "COLLECTION",
  AUTHOR: "AUTHOR",
  CATEGORY: "CATEGORY",
  NAME: "NAME",
  CATEGORY_NAME_DESCRIPTION: "CATEGORY_NAME_DESCRIPTION",
  SAVE: "SAVE",
  INVALID_FIELD: "INVALID_FIELD",
  CATEGORY_SAVED: "CATEGORY_SAVED",
  SAVED_CONTENT: "SAVED_CONTENT",
  ERR_NETWORK: "ERR_NETWORK",
  DATE_OF_BIRTH: "DATE_OF_BIRTH",
  TITLE: "TITLE",
  SYNOPSIS: "SYNOPSIS",
  RELEASE_DATE: "RELEASE_DATE",
  LINK: "LINK",
  SELECT: "SELECT"
}

export const RegexConstants = {
  NAME_REGEX: /^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$/
}
