
name: Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  server-tests:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend-server

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check diff
        run: |
          if git diff --exit-code; then
              echo "HAS_CHANGES=false" >>${GITHUB_ENV}
          else
              echo "HAS_CHANGES=true" >>${GITHUB_ENV}
          fi

          if [[ env.HAS_CHANGES == 'true' ]]; then
              - name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                  java-version: '17'
                  distribution: 'oracle'

              - name: Grant Permissions to gradlew
                run: chmod +x gradlew

              - name: Run tests
                run: ./gradlew clean build check
          fi

